[package]
name = "bbs-accum"
version = "0.1.0"
authors = ["Andrew Whitehead <cywolf@gmail.com>"]
edition = "2018"

[dependencies]
blake2 = "0.9"
bls12_381 = { version = "0.5", features = ["experimental"] }
ff = "0.10"
group = "0.10"
rand = "0.8"
subtle = "2.4"
